# -*- coding: utf-8 -*-
"""Spark_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRnEO-ArP3pZbTKfFQUsCJMJhgOafa7y
"""

from pyspark.sql.functions import col

df = (spark.read.option('header', True)
  .option('sep',',')
  .option('inferSchema', True)
  .csv('owid-covid-data.csv'))

data1=df.select('iso_code','location','date', 'new_cases')
  .where((col('date')>"2021-03-23")
    &(col('date')<="2021-03-31")
    &(col('iso_code').startswith('OWID_') ==False)
    )
  .groupBy('location').max('new_cases')
  .orderBy(col('max(new_cases)').desc())
  .take(10)

data2 = spark.createDataFrame(data1)

data3 = data2.select('max(new_cases)', 'location')
  .join(df.select('date', 'new_cases', col('location').alias('loc')).where((col('date')>"2021-03-23")&(col('date')<="2021-03-31")), (col('max(new_cases)') ==  col('new_cases'))&(col('location') ==  col('loc')),'left')

data3.select('date','location', 'max(new_cases)').show()