# -*- coding: utf-8 -*-
"""Spark_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_d-9pVTPqy059y2uEmesO8e13ZscMk3
"""

from pyspark.sql.functions import col

df = (spark.read.option('header', True)
  .option('sep',',')
  .option('inferSchema', True)
  .csv('owid-covid-data.csv'))

df.select('iso_code','location','date', (col('total_cases').cast('int')/col('population').cast('int')*100).cast('int')
  .alias('PRIC')).where(col('iso_code').rlike('^((?!OWID).)*$') 
    & (col('date') < "2021-03-31")
    )
  .groupBy('location', 'iso_code')
  .max('PRIC')
  .orderBy(col('max(PRIC)').desc())
  .show(15)