# -*- coding: utf-8 -*-
"""Spark_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRnEO-ArP3pZbTKfFQUsCJMJhgOafa7y
"""

from pyspark.sql.functions import col

df = (spark.read.option('header', True)
  .option('sep',',')
  .option('inferSchema', True)
  .csv('owid-covid-data.csv'))

df.select('iso_code','location','date', 'new_cases')
    .where((col('date')>"2021-03-23")&(col('date')<="2021-03-31"))
    .groupBy('location')
    .max('new_cases')
    .orderBy(col('max(new_cases)')
    .desc()
    )
  .show(15)